name: GitHub OIDC Terraform Test

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  oidc-terraform-test:
    name: Test AWS OIDC Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dev/vpc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::442847318797:role/tf-deploy-dev

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.8

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
